package com.abmanzano.kafkasamplespring.dto.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 shortId = 2;</code>
     * @return The shortId.
     */
    int getShortId();

    /**
     * <code>int32 intId = 3;</code>
     * @return The intId.
     */
    int getIntId();

    /**
     * <code>int64 longId = 4;</code>
     * @return The longId.
     */
    long getLongId();

    /**
     * <code>string charId = 5;</code>
     * @return The charId.
     */
    String getCharId();
    /**
     * <code>string charId = 5;</code>
     * @return The bytes for charId.
     */
    com.google.protobuf.ByteString
        getCharIdBytes();

    /**
     * <code>bytes byteId = 6;</code>
     * @return The byteId.
     */
    com.google.protobuf.ByteString getByteId();

    /**
     * <code>repeated .Product products = 7;</code>
     */
    java.util.List<ProductOuterClass.Product> 
        getProductsList();
    /**
     * <code>repeated .Product products = 7;</code>
     */
    ProductOuterClass.Product getProducts(int index);
    /**
     * <code>repeated .Product products = 7;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .Product products = 7;</code>
     */
    java.util.List<? extends ProductOuterClass.ProductOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .Product products = 7;</code>
     */
    ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
        int index);

    /**
     * <code>float total = 8;</code>
     * @return The total.
     */
    float getTotal();

    /**
     * <code>bool paid = 9;</code>
     * @return The paid.
     */
    boolean getPaid();

    /**
     * <code>int32 date = 10;</code>
     * @return The date.
     */
    int getDate();
  }
  /**
   * Protobuf type {@code OrderRequest}
   */
  public static final class OrderRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderRequest)
      OrderRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderRequest.newBuilder() to construct.
    private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderRequest() {
      id_ = "";
      charId_ = "";
      byteId_ = com.google.protobuf.ByteString.EMPTY;
      products_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              shortId_ = input.readInt32();
              break;
            }
            case 24: {

              intId_ = input.readInt32();
              break;
            }
            case 32: {

              longId_ = input.readInt64();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              charId_ = s;
              break;
            }
            case 50: {

              byteId_ = input.readBytes();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                products_ = new java.util.ArrayList<ProductOuterClass.Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              products_.add(
                  input.readMessage(ProductOuterClass.Product.parser(), extensionRegistry));
              break;
            }
            case 69: {

              total_ = input.readFloat();
              break;
            }
            case 72: {

              paid_ = input.readBool();
              break;
            }
            case 80: {

              date_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          products_ = java.util.Collections.unmodifiableList(products_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Order.internal_static_OrderRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Order.internal_static_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderRequest.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORTID_FIELD_NUMBER = 2;
    private int shortId_;
    /**
     * <code>int32 shortId = 2;</code>
     * @return The shortId.
     */
    @Override
    public int getShortId() {
      return shortId_;
    }

    public static final int INTID_FIELD_NUMBER = 3;
    private int intId_;
    /**
     * <code>int32 intId = 3;</code>
     * @return The intId.
     */
    @Override
    public int getIntId() {
      return intId_;
    }

    public static final int LONGID_FIELD_NUMBER = 4;
    private long longId_;
    /**
     * <code>int64 longId = 4;</code>
     * @return The longId.
     */
    @Override
    public long getLongId() {
      return longId_;
    }

    public static final int CHARID_FIELD_NUMBER = 5;
    private volatile Object charId_;
    /**
     * <code>string charId = 5;</code>
     * @return The charId.
     */
    @Override
    public String getCharId() {
      Object ref = charId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        charId_ = s;
        return s;
      }
    }
    /**
     * <code>string charId = 5;</code>
     * @return The bytes for charId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCharIdBytes() {
      Object ref = charId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        charId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTEID_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString byteId_;
    /**
     * <code>bytes byteId = 6;</code>
     * @return The byteId.
     */
    @Override
    public com.google.protobuf.ByteString getByteId() {
      return byteId_;
    }

    public static final int PRODUCTS_FIELD_NUMBER = 7;
    private java.util.List<ProductOuterClass.Product> products_;
    /**
     * <code>repeated .Product products = 7;</code>
     */
    @Override
    public java.util.List<ProductOuterClass.Product> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 7;</code>
     */
    @Override
    public java.util.List<? extends ProductOuterClass.ProductOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 7;</code>
     */
    @Override
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .Product products = 7;</code>
     */
    @Override
    public ProductOuterClass.Product getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .Product products = 7;</code>
     */
    @Override
    public ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    public static final int TOTAL_FIELD_NUMBER = 8;
    private float total_;
    /**
     * <code>float total = 8;</code>
     * @return The total.
     */
    @Override
    public float getTotal() {
      return total_;
    }

    public static final int PAID_FIELD_NUMBER = 9;
    private boolean paid_;
    /**
     * <code>bool paid = 9;</code>
     * @return The paid.
     */
    @Override
    public boolean getPaid() {
      return paid_;
    }

    public static final int DATE_FIELD_NUMBER = 10;
    private int date_;
    /**
     * <code>int32 date = 10;</code>
     * @return The date.
     */
    @Override
    public int getDate() {
      return date_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (shortId_ != 0) {
        output.writeInt32(2, shortId_);
      }
      if (intId_ != 0) {
        output.writeInt32(3, intId_);
      }
      if (longId_ != 0L) {
        output.writeInt64(4, longId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(charId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, charId_);
      }
      if (!byteId_.isEmpty()) {
        output.writeBytes(6, byteId_);
      }
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(7, products_.get(i));
      }
      if (Float.floatToRawIntBits(total_) != 0) {
        output.writeFloat(8, total_);
      }
      if (paid_ != false) {
        output.writeBool(9, paid_);
      }
      if (date_ != 0) {
        output.writeInt32(10, date_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (shortId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, shortId_);
      }
      if (intId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, intId_);
      }
      if (longId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, longId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(charId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, charId_);
      }
      if (!byteId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, byteId_);
      }
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, products_.get(i));
      }
      if (Float.floatToRawIntBits(total_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, total_);
      }
      if (paid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, paid_);
      }
      if (date_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, date_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderRequest)) {
        return super.equals(obj);
      }
      OrderRequest other = (OrderRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getShortId()
          != other.getShortId()) return false;
      if (getIntId()
          != other.getIntId()) return false;
      if (getLongId()
          != other.getLongId()) return false;
      if (!getCharId()
          .equals(other.getCharId())) return false;
      if (!getByteId()
          .equals(other.getByteId())) return false;
      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (Float.floatToIntBits(getTotal())
          != Float.floatToIntBits(
              other.getTotal())) return false;
      if (getPaid()
          != other.getPaid()) return false;
      if (getDate()
          != other.getDate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + SHORTID_FIELD_NUMBER;
      hash = (53 * hash) + getShortId();
      hash = (37 * hash) + INTID_FIELD_NUMBER;
      hash = (53 * hash) + getIntId();
      hash = (37 * hash) + LONGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongId());
      hash = (37 * hash) + CHARID_FIELD_NUMBER;
      hash = (53 * hash) + getCharId().hashCode();
      hash = (37 * hash) + BYTEID_FIELD_NUMBER;
      hash = (53 * hash) + getByteId().hashCode();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getTotal());
      hash = (37 * hash) + PAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPaid());
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderRequest)
        OrderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Order.internal_static_OrderRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Order.internal_static_OrderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderRequest.class, Builder.class);
      }

      // Construct using Order.OrderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        shortId_ = 0;

        intId_ = 0;

        longId_ = 0L;

        charId_ = "";

        byteId_ = com.google.protobuf.ByteString.EMPTY;

        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productsBuilder_.clear();
        }
        total_ = 0F;

        paid_ = false;

        date_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Order.internal_static_OrderRequest_descriptor;
      }

      @Override
      public OrderRequest getDefaultInstanceForType() {
        return OrderRequest.getDefaultInstance();
      }

      @Override
      public OrderRequest build() {
        OrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OrderRequest buildPartial() {
        OrderRequest result = new OrderRequest(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.shortId_ = shortId_;
        result.intId_ = intId_;
        result.longId_ = longId_;
        result.charId_ = charId_;
        result.byteId_ = byteId_;
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
        result.total_ = total_;
        result.paid_ = paid_;
        result.date_ = date_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderRequest) {
          return mergeFrom((OrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderRequest other) {
        if (other == OrderRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getShortId() != 0) {
          setShortId(other.getShortId());
        }
        if (other.getIntId() != 0) {
          setIntId(other.getIntId());
        }
        if (other.getLongId() != 0L) {
          setLongId(other.getLongId());
        }
        if (!other.getCharId().isEmpty()) {
          charId_ = other.charId_;
          onChanged();
        }
        if (other.getByteId() != com.google.protobuf.ByteString.EMPTY) {
          setByteId(other.getByteId());
        }
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        if (other.getTotal() != 0F) {
          setTotal(other.getTotal());
        }
        if (other.getPaid() != false) {
          setPaid(other.getPaid());
        }
        if (other.getDate() != 0) {
          setDate(other.getDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int shortId_ ;
      /**
       * <code>int32 shortId = 2;</code>
       * @return The shortId.
       */
      @Override
      public int getShortId() {
        return shortId_;
      }
      /**
       * <code>int32 shortId = 2;</code>
       * @param value The shortId to set.
       * @return This builder for chaining.
       */
      public Builder setShortId(int value) {
        
        shortId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 shortId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearShortId() {
        
        shortId_ = 0;
        onChanged();
        return this;
      }

      private int intId_ ;
      /**
       * <code>int32 intId = 3;</code>
       * @return The intId.
       */
      @Override
      public int getIntId() {
        return intId_;
      }
      /**
       * <code>int32 intId = 3;</code>
       * @param value The intId to set.
       * @return This builder for chaining.
       */
      public Builder setIntId(int value) {
        
        intId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntId() {
        
        intId_ = 0;
        onChanged();
        return this;
      }

      private long longId_ ;
      /**
       * <code>int64 longId = 4;</code>
       * @return The longId.
       */
      @Override
      public long getLongId() {
        return longId_;
      }
      /**
       * <code>int64 longId = 4;</code>
       * @param value The longId to set.
       * @return This builder for chaining.
       */
      public Builder setLongId(long value) {
        
        longId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongId() {
        
        longId_ = 0L;
        onChanged();
        return this;
      }

      private Object charId_ = "";
      /**
       * <code>string charId = 5;</code>
       * @return The charId.
       */
      public String getCharId() {
        Object ref = charId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          charId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string charId = 5;</code>
       * @return The bytes for charId.
       */
      public com.google.protobuf.ByteString
          getCharIdBytes() {
        Object ref = charId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          charId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string charId = 5;</code>
       * @param value The charId to set.
       * @return This builder for chaining.
       */
      public Builder setCharId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        charId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string charId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCharId() {
        
        charId_ = getDefaultInstance().getCharId();
        onChanged();
        return this;
      }
      /**
       * <code>string charId = 5;</code>
       * @param value The bytes for charId to set.
       * @return This builder for chaining.
       */
      public Builder setCharIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        charId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString byteId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes byteId = 6;</code>
       * @return The byteId.
       */
      @Override
      public com.google.protobuf.ByteString getByteId() {
        return byteId_;
      }
      /**
       * <code>bytes byteId = 6;</code>
       * @param value The byteId to set.
       * @return This builder for chaining.
       */
      public Builder setByteId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        byteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes byteId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearByteId() {
        
        byteId_ = getDefaultInstance().getByteId();
        onChanged();
        return this;
      }

      private java.util.List<ProductOuterClass.Product> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          products_ = new java.util.ArrayList<ProductOuterClass.Product>(products_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated .Product products = 7;</code>
       */
      public java.util.List<ProductOuterClass.Product> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public ProductOuterClass.Product getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder setProducts(
          int index, ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder setProducts(
          int index, ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder addProducts(ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder addProducts(
          int index, ProductOuterClass.Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder addProducts(
          ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder addProducts(
          int index, ProductOuterClass.Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder addAllProducts(
          Iterable<? extends ProductOuterClass.Product> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public ProductOuterClass.Product.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public ProductOuterClass.ProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public java.util.List<? extends ProductOuterClass.ProductOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public ProductOuterClass.Product.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            ProductOuterClass.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public ProductOuterClass.Product.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, ProductOuterClass.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 7;</code>
       */
      public java.util.List<ProductOuterClass.Product.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      private float total_ ;
      /**
       * <code>float total = 8;</code>
       * @return The total.
       */
      @Override
      public float getTotal() {
        return total_;
      }
      /**
       * <code>float total = 8;</code>
       * @param value The total to set.
       * @return This builder for chaining.
       */
      public Builder setTotal(float value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float total = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotal() {
        
        total_ = 0F;
        onChanged();
        return this;
      }

      private boolean paid_ ;
      /**
       * <code>bool paid = 9;</code>
       * @return The paid.
       */
      @Override
      public boolean getPaid() {
        return paid_;
      }
      /**
       * <code>bool paid = 9;</code>
       * @param value The paid to set.
       * @return This builder for chaining.
       */
      public Builder setPaid(boolean value) {
        
        paid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool paid = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaid() {
        
        paid_ = false;
        onChanged();
        return this;
      }

      private int date_ ;
      /**
       * <code>int32 date = 10;</code>
       * @return The date.
       */
      @Override
      public int getDate() {
        return date_;
      }
      /**
       * <code>int32 date = 10;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(int value) {
        
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 date = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderRequest)
    }

    // @@protoc_insertion_point(class_scope:OrderRequest)
    private static final OrderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderRequest();
    }

    public static OrderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRequest>
        PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
      @Override
      public OrderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public OrderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Order.proto\032\rProduct.proto\"\261\001\n\014OrderRe" +
      "quest\022\n\n\002id\030\001 \001(\t\022\017\n\007shortId\030\002 \001(\005\022\r\n\005in" +
      "tId\030\003 \001(\005\022\016\n\006longId\030\004 \001(\003\022\016\n\006charId\030\005 \001(" +
      "\t\022\016\n\006byteId\030\006 \001(\014\022\032\n\010products\030\007 \003(\0132\010.Pr" +
      "oduct\022\r\n\005total\030\010 \001(\002\022\014\n\004paid\030\t \001(\010\022\014\n\004da" +
      "te\030\n \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProductOuterClass.getDescriptor(),
        });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new String[] { "Id", "ShortId", "IntId", "LongId", "CharId", "ByteId", "Products", "Total", "Paid", "Date", });
    ProductOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
