package com.abmanzano.kafkasamplespring.dto.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.Brand brand = 3;</code>
     * @return Whether the brand field is set.
     */
    boolean hasBrand();
    /**
     * <code>.Brand brand = 3;</code>
     * @return The brand.
     */
    BrandOuterClass.Brand getBrand();
    /**
     * <code>.Brand brand = 3;</code>
     */
    BrandOuterClass.BrandOrBuilder getBrandOrBuilder();

    /**
     * <code>.Product.ProductCondition productCondition = 4;</code>
     * @return The enum numeric value on the wire for productCondition.
     */
    int getProductConditionValue();
    /**
     * <code>.Product.ProductCondition productCondition = 4;</code>
     * @return The productCondition.
     */
    Product.ProductCondition getProductCondition();

    /**
     * <code>bytes image = 5;</code>
     * @return The image.
     */
    com.google.protobuf.ByteString getImage();

    /**
     * <code>float price = 6;</code>
     * @return The price.
     */
    float getPrice();

    /**
     * <code>int32 quantity = 7;</code>
     * @return The quantity.
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code Product}
   */
  public static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      id_ = "";
      name_ = "";
      productCondition_ = 0;
      image_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              BrandOuterClass.Brand.Builder subBuilder = null;
              if (brand_ != null) {
                subBuilder = brand_.toBuilder();
              }
              brand_ = input.readMessage(BrandOuterClass.Brand.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(brand_);
                brand_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              productCondition_ = rawValue;
              break;
            }
            case 42: {

              image_ = input.readBytes();
              break;
            }
            case 53: {

              price_ = input.readFloat();
              break;
            }
            case 56: {

              quantity_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductOuterClass.internal_static_Product_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductOuterClass.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Product.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Product.ProductCondition}
     */
    public enum ProductCondition
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW = 0;</code>
       */
      NEW(0),
      /**
       * <code>AS_GOOD_AS_NEW = 1;</code>
       */
      AS_GOOD_AS_NEW(1),
      /**
       * <code>GOOD = 2;</code>
       */
      GOOD(2),
      /**
       * <code>WITH_SIGNE_OF_USE = 3;</code>
       */
      WITH_SIGNE_OF_USE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NEW = 0;</code>
       */
      public static final int NEW_VALUE = 0;
      /**
       * <code>AS_GOOD_AS_NEW = 1;</code>
       */
      public static final int AS_GOOD_AS_NEW_VALUE = 1;
      /**
       * <code>GOOD = 2;</code>
       */
      public static final int GOOD_VALUE = 2;
      /**
       * <code>WITH_SIGNE_OF_USE = 3;</code>
       */
      public static final int WITH_SIGNE_OF_USE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ProductCondition valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ProductCondition forNumber(int value) {
        switch (value) {
          case 0: return NEW;
          case 1: return AS_GOOD_AS_NEW;
          case 2: return GOOD;
          case 3: return WITH_SIGNE_OF_USE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProductCondition>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ProductCondition> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProductCondition>() {
              public ProductCondition findValueByNumber(int number) {
                return ProductCondition.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Product.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProductCondition[] VALUES = values();

      public static ProductCondition valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ProductCondition(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Product.ProductCondition)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private BrandOuterClass.Brand brand_;
    /**
     * <code>.Brand brand = 3;</code>
     * @return Whether the brand field is set.
     */
    @Override
    public boolean hasBrand() {
      return brand_ != null;
    }
    /**
     * <code>.Brand brand = 3;</code>
     * @return The brand.
     */
    @Override
    public BrandOuterClass.Brand getBrand() {
      return brand_ == null ? BrandOuterClass.Brand.getDefaultInstance() : brand_;
    }
    /**
     * <code>.Brand brand = 3;</code>
     */
    @Override
    public BrandOuterClass.BrandOrBuilder getBrandOrBuilder() {
      return getBrand();
    }

    public static final int PRODUCTCONDITION_FIELD_NUMBER = 4;
    private int productCondition_;
    /**
     * <code>.Product.ProductCondition productCondition = 4;</code>
     * @return The enum numeric value on the wire for productCondition.
     */
    @Override public int getProductConditionValue() {
      return productCondition_;
    }
    /**
     * <code>.Product.ProductCondition productCondition = 4;</code>
     * @return The productCondition.
     */
    @Override public ProductCondition getProductCondition() {
      @SuppressWarnings("deprecation")
      ProductCondition result = ProductCondition.valueOf(productCondition_);
      return result == null ? ProductCondition.UNRECOGNIZED : result;
    }

    public static final int IMAGE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString image_;
    /**
     * <code>bytes image = 5;</code>
     * @return The image.
     */
    @Override
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private float price_;
    /**
     * <code>float price = 6;</code>
     * @return The price.
     */
    @Override
    public float getPrice() {
      return price_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 7;
    private int quantity_;
    /**
     * <code>int32 quantity = 7;</code>
     * @return The quantity.
     */
    @Override
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (brand_ != null) {
        output.writeMessage(3, getBrand());
      }
      if (productCondition_ != ProductCondition.NEW.getNumber()) {
        output.writeEnum(4, productCondition_);
      }
      if (!image_.isEmpty()) {
        output.writeBytes(5, image_);
      }
      if (Float.floatToRawIntBits(price_) != 0) {
        output.writeFloat(6, price_);
      }
      if (quantity_ != 0) {
        output.writeInt32(7, quantity_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (brand_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBrand());
      }
      if (productCondition_ != ProductCondition.NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, productCondition_);
      }
      if (!image_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, image_);
      }
      if (Float.floatToRawIntBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, price_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, quantity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Product)) {
        return super.equals(obj);
      }
      Product other = (Product) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasBrand() != other.hasBrand()) return false;
      if (hasBrand()) {
        if (!getBrand()
            .equals(other.getBrand())) return false;
      }
      if (productCondition_ != other.productCondition_) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (Float.floatToIntBits(getPrice())
          != Float.floatToIntBits(
              other.getPrice())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasBrand()) {
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + getBrand().hashCode();
      }
      hash = (37 * hash) + PRODUCTCONDITION_FIELD_NUMBER;
      hash = (53 * hash) + productCondition_;
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPrice());
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductOuterClass.internal_static_Product_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductOuterClass.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Product.class, Builder.class);
      }

      // Construct using ProductOuterClass.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        if (brandBuilder_ == null) {
          brand_ = null;
        } else {
          brand_ = null;
          brandBuilder_ = null;
        }
        productCondition_ = 0;

        image_ = com.google.protobuf.ByteString.EMPTY;

        price_ = 0F;

        quantity_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductOuterClass.internal_static_Product_descriptor;
      }

      @Override
      public Product getDefaultInstanceForType() {
        return Product.getDefaultInstance();
      }

      @Override
      public Product build() {
        Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Product buildPartial() {
        Product result = new Product(this);
        result.id_ = id_;
        result.name_ = name_;
        if (brandBuilder_ == null) {
          result.brand_ = brand_;
        } else {
          result.brand_ = brandBuilder_.build();
        }
        result.productCondition_ = productCondition_;
        result.image_ = image_;
        result.price_ = price_;
        result.quantity_ = quantity_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Product) {
          return mergeFrom((Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Product other) {
        if (other == Product.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasBrand()) {
          mergeBrand(other.getBrand());
        }
        if (other.productCondition_ != 0) {
          setProductConditionValue(other.getProductConditionValue());
        }
        if (other.getImage() != com.google.protobuf.ByteString.EMPTY) {
          setImage(other.getImage());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private BrandOuterClass.Brand brand_;
      private com.google.protobuf.SingleFieldBuilderV3<
          BrandOuterClass.Brand, BrandOuterClass.Brand.Builder, BrandOuterClass.BrandOrBuilder> brandBuilder_;
      /**
       * <code>.Brand brand = 3;</code>
       * @return Whether the brand field is set.
       */
      public boolean hasBrand() {
        return brandBuilder_ != null || brand_ != null;
      }
      /**
       * <code>.Brand brand = 3;</code>
       * @return The brand.
       */
      public BrandOuterClass.Brand getBrand() {
        if (brandBuilder_ == null) {
          return brand_ == null ? BrandOuterClass.Brand.getDefaultInstance() : brand_;
        } else {
          return brandBuilder_.getMessage();
        }
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public Builder setBrand(BrandOuterClass.Brand value) {
        if (brandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          brand_ = value;
          onChanged();
        } else {
          brandBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public Builder setBrand(
          BrandOuterClass.Brand.Builder builderForValue) {
        if (brandBuilder_ == null) {
          brand_ = builderForValue.build();
          onChanged();
        } else {
          brandBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public Builder mergeBrand(BrandOuterClass.Brand value) {
        if (brandBuilder_ == null) {
          if (brand_ != null) {
            brand_ =
              BrandOuterClass.Brand.newBuilder(brand_).mergeFrom(value).buildPartial();
          } else {
            brand_ = value;
          }
          onChanged();
        } else {
          brandBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public Builder clearBrand() {
        if (brandBuilder_ == null) {
          brand_ = null;
          onChanged();
        } else {
          brand_ = null;
          brandBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public BrandOuterClass.Brand.Builder getBrandBuilder() {
        
        onChanged();
        return getBrandFieldBuilder().getBuilder();
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      public BrandOuterClass.BrandOrBuilder getBrandOrBuilder() {
        if (brandBuilder_ != null) {
          return brandBuilder_.getMessageOrBuilder();
        } else {
          return brand_ == null ?
              BrandOuterClass.Brand.getDefaultInstance() : brand_;
        }
      }
      /**
       * <code>.Brand brand = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BrandOuterClass.Brand, BrandOuterClass.Brand.Builder, BrandOuterClass.BrandOrBuilder> 
          getBrandFieldBuilder() {
        if (brandBuilder_ == null) {
          brandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BrandOuterClass.Brand, BrandOuterClass.Brand.Builder, BrandOuterClass.BrandOrBuilder>(
                  getBrand(),
                  getParentForChildren(),
                  isClean());
          brand_ = null;
        }
        return brandBuilder_;
      }

      private int productCondition_ = 0;
      /**
       * <code>.Product.ProductCondition productCondition = 4;</code>
       * @return The enum numeric value on the wire for productCondition.
       */
      @Override public int getProductConditionValue() {
        return productCondition_;
      }
      /**
       * <code>.Product.ProductCondition productCondition = 4;</code>
       * @param value The enum numeric value on the wire for productCondition to set.
       * @return This builder for chaining.
       */
      public Builder setProductConditionValue(int value) {
        
        productCondition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Product.ProductCondition productCondition = 4;</code>
       * @return The productCondition.
       */
      @Override
      public ProductCondition getProductCondition() {
        @SuppressWarnings("deprecation")
        ProductCondition result = ProductCondition.valueOf(productCondition_);
        return result == null ? ProductCondition.UNRECOGNIZED : result;
      }
      /**
       * <code>.Product.ProductCondition productCondition = 4;</code>
       * @param value The productCondition to set.
       * @return This builder for chaining.
       */
      public Builder setProductCondition(ProductCondition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        productCondition_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Product.ProductCondition productCondition = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductCondition() {
        
        productCondition_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes image = 5;</code>
       * @return The image.
       */
      @Override
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      /**
       * <code>bytes image = 5;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes image = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 6;</code>
       * @return The price.
       */
      @Override
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 6;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 7;</code>
       * @return The quantity.
       */
      @Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 7;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Product();
    }

    public static Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @Override
    public Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rProduct.proto\032\013Brand.proto\"\361\001\n\007Product" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\025\n\005brand\030\003 \001(" +
      "\0132\006.Brand\0223\n\020productCondition\030\004 \001(\0162\031.Pr" +
      "oduct.ProductCondition\022\r\n\005image\030\005 \001(\014\022\r\n" +
      "\005price\030\006 \001(\002\022\020\n\010quantity\030\007 \001(\005\"P\n\020Produc" +
      "tCondition\022\007\n\003NEW\020\000\022\022\n\016AS_GOOD_AS_NEW\020\001\022" +
      "\010\n\004GOOD\020\002\022\025\n\021WITH_SIGNE_OF_USE\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BrandOuterClass.getDescriptor(),
        });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new String[] { "Id", "Name", "Brand", "ProductCondition", "Image", "Price", "Quantity", });
    BrandOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
